spring:
    application:
        name: notification

    mvc:
        apiversion:
            use:
                path-segment: 1
            default: 1
            supported: 1

    kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    threads:
        virtual:
            enabled: true

logging:
    aspect:
        include-args: false

app:
    notification:
        kafka:
            invitation-consumer-group: ${INVITATION_CONSUMER_GROUP:notification-meeting-invitations}
            invite-invalidated-consumer-group: ${INVITE_INVALIDATED_CONSUMER_GROUP:notification-meeting-invite-invalidated}
            invitee-responded-consumer-group: ${INVITEE_RESPONDED_CONSUMER_GROUP:notification-invitee-responded}
