spring:
    kafka:
        bootstrap-servers: localhost:9094

    datasource:
        url: jdbc:postgresql://localhost:5432/notification
        username: ${POSTGRES_USER:smiski_user}
        password: ${POSTGRES_PASSWORD:smiski_secret}

    data:
        redis:
            host: localhost
            port: 8284
            password:
