syntax = "proto3";

package io.github.smiskinext.event.meet.v1;

option java_multiple_files = true;
option java_package = "io.github.smiskinext.event.meet.v1";

message InviteeAccepted {
  string event_id = 1;
  string tenant_id = 2;
  string meeting_id = 3;
  string inviter_id = 4;
  string invitee_id = 5;
  string invitee_email = 6;
  string status = 7;
  string accepted_at = 8;
  string meeting_title = 9;
  string start_time = 10;
  string end_time = 11;
  string zone_id = 12;
  string organizer_email = 13;
  string organizer_display_name = 14;
  string invitee_display_name = 15;
  string calendar_uid = 16;
  int32 calendar_sequence = 17;
  string issue_id = 18;
  string issue_key = 19;
  string project_key = 20;
  string short_code = 21;
}

message InviteeDeclined {
  string event_id = 1;
  string tenant_id = 2;
  string meeting_id = 3;
  string inviter_id = 4;
  string invitee_id = 5;
  string invitee_email = 6;
  string status = 7;
  string declined_at = 8;
  string meeting_title = 9;
  string start_time = 10;
  string end_time = 11;
  string zone_id = 12;
  string organizer_email = 13;
  string organizer_display_name = 14;
  string invitee_display_name = 15;
  string calendar_uid = 16;
  int32 calendar_sequence = 17;
  string issue_id = 18;
  string issue_key = 19;
  string project_key = 20;
  string short_code = 21;
}

message InviteeTentative {
  string event_id = 1;
  string tenant_id = 2;
  string meeting_id = 3;
  string inviter_id = 4;
  string invitee_id = 5;
  string invitee_email = 6;
  string status = 7;
  string tentative_at = 8;
  string meeting_title = 9;
  string start_time = 10;
  string end_time = 11;
  string zone_id = 12;
  string organizer_email = 13;
  string organizer_display_name = 14;
  string invitee_display_name = 15;
  string calendar_uid = 16;
  int32 calendar_sequence = 17;
  string issue_id = 18;
  string issue_key = 19;
  string project_key = 20;
  string short_code = 21;
}
