syntax = "proto3";

package io.github.smiskinext.event.meet.v1;

option java_multiple_files = true;
option java_package = "io.github.smiskinext.event.meet.v1";

message MeetingInvitationsSent {
  reserved 7;
  reserved "invitee_tokens";

  string meeting_id = 1;
  string tenant_id = 2;
  string meeting_title = 3;
  string meeting_short_code = 4;
  string start_time = 5;
  repeated InviteeInfo invitees = 6;
  string zone_id = 8;
  string end_time = 9;

  message InviteeInfo {
    string account_id = 1;
    string email = 2;
    string display_name = 3;
    string token = 4;
  }
}
