syntax = "proto3";

package io.github.smiskinext.event.meet.v1;

option java_multiple_files = true;
option java_package = "io.github.smiskinext.event.meet.v1";

message MeetingSnapshot {
  string meeting_id = 1;
  string tenant_id = 2;
  string host_id = 3;
  string short_code = 4;
  string type = 5;
  string status = 6;
  string title = 7;
  string description = 8;
  IssueLink issue_link = 9;
  string start_time = 10;
  string end_time = 11;
  MeetingSettings settings = 12;
  string created_at = 13;
  string zone_id = 14;
}

message MeetingSettings {
  string admission_policy = 1;
  int32 max_participants = 2;
  bool allow_screen_share = 3;
  bool chat_enabled = 4;
  bool allow_microphone = 5;
  bool allow_video = 6;
}

message IssueLink {
  string issue_id = 1;
  string issue_key = 2;
  string project_key = 3;
}

message MeetingInfoUpdated {
  string meeting_id = 1;
  string tenant_id = 2;
  string host_id = 3;
  string updated_by = 4;
  string status = 5;
  MeetingInfoSnapshot old_info = 6;
  MeetingInfoSnapshot new_info = 7;
  string updated_at = 8;
}

message MeetingInfoSnapshot {
  string title = 1;
  string description = 2;
  IssueLink issue_link = 3;
  string zone_id = 4;
  string start_time = 5;
  string end_time = 6;
}

message MeetingSettingsUpdated {
  string meeting_id = 1;
  string tenant_id = 2;
  string host_id = 3;
  string updated_by = 4;
  string status = 5;
  MeetingSettings old_settings = 6;
  MeetingSettings new_settings = 7;
  string updated_at = 8;
}
