blank_issues_enabled: false
contact_links:
    - name: 💬 Discussions
      url: https://github.com/SmiskiNext/smiski/discussions
      about:
          For support, troubleshooting, how-to questions, and general
          discussion.
