apiVersion: v1
kind: Secret
metadata:
    name: chat-management-secrets
    namespace: default
type: Opaque
stringData:
    livekit-api-key: 'zms-livekit-key'
    livekit-api-secret: 'change-me-livekit-secret-must-be-at-least-32-chars'
    chat-jwt-secret: 'change-me-chat-jwt-secret-must-be-at-least-32-chars'
