apiVersion: v1
kind: Secret
metadata:
    name: livekit-secrets
    namespace: livekit-system
type: Opaque
stringData:
    api-key: 'zms-livekit-key'
    api-secret: 'change-me-livekit-secret-must-be-at-least-32-chars'
