apiVersion: v1
kind: Secret
metadata:
    name: rustfs-credentials
    namespace: rustfs-system
type: Opaque
stringData:
    access-key: 'rustfs-access-key'
    secret-key: 'rustfs-secret-key-change-me'
