apiVersion: v1
kind: Secret
metadata:
    name: chat-management-secrets
    namespace: default
type: Opaque
stringData:
    livekit-api-key: 'MUST_CHANGE_IN_PRODUCTION'
    livekit-api-secret: 'MUST_CHANGE_IN_PRODUCTION'
    chat-jwt-secret: 'MUST_CHANGE_IN_PRODUCTION'
