apiVersion: v1
kind: Secret
metadata:
    name: livekit-secrets
    namespace: livekit-system
type: Opaque
stringData:
    api-key: 'MUST_CHANGE_IN_PRODUCTION'
    api-secret: 'MUST_CHANGE_IN_PRODUCTION'
