apiVersion: v1
kind: Secret
metadata:
    name: meeting-management-secrets
    namespace: default
type: Opaque
stringData:
    db-username: 'MUST_CHANGE_IN_PRODUCTION'
    db-password: 'MUST_CHANGE_IN_PRODUCTION'
    cursor-secret: 'MUST_CHANGE_IN_PRODUCTION'
    livekit-api-key: 'MUST_CHANGE_IN_PRODUCTION'
    livekit-api-secret: 'MUST_CHANGE_IN_PRODUCTION'
    recording-s3-access-key: 'MUST_CHANGE_IN_PRODUCTION'
    recording-s3-secret-key: 'MUST_CHANGE_IN_PRODUCTION'
