apiVersion: v1
kind: Secret
metadata:
    name: user-management-secrets
    namespace: default
type: Opaque
stringData:
    jwt-secret: 'MUST_CHANGE_IN_PRODUCTION'
    cursor-secret: 'MUST_CHANGE_IN_PRODUCTION'
    db-username: 'MUST_CHANGE_IN_PRODUCTION'
    db-password: 'MUST_CHANGE_IN_PRODUCTION'
    recaptcha-secret-key: 'MUST_CHANGE_IN_PRODUCTION'
