server:
    port: 8182

spring:
    datasource:
        url: jdbc:postgresql://localhost:8282/zms_meetings
        username: ${POSTGRES_USER:zms_user}
        password: ${POSTGRES_PASSWORD:zms_secret}

    kafka:
        bootstrap-servers: localhost:9094

    data:
        redis:
            host: localhost
            port: 8284
            password:

app:
    livekit:
        url: http://localhost:7880
        ws-url: ws://localhost:7880
        webhook-url: http://localhost:30000/api/1/webhooks/livekit
        recording:
            egress-endpoint: http://rustfs:9000
