spring:
    datasource:
        url: jdbc:postgresql://localhost:8283/tenant
        username: ${POSTGRES_USER:smiski_user}
        password: ${POSTGRES_PASSWORD:smiski_secret}

    kafka:
        bootstrap-servers: localhost:9094
