server:
    port: 8183

spring:
    datasource:
        url: jdbc:postgresql://localhost:8283/zms_tenants
        username: ${POSTGRES_USER:zms_user}
        password: ${POSTGRES_PASSWORD:zms_secret}

    kafka:
        bootstrap-servers: localhost:9094

app:
    forge:
        environment-type: DEVELOPMENT

springdoc:
    servers:
        - url: http://localhost:30000
