import type * as Preset from '@docusaurus/preset-classic';
import type { Config } from '@docusaurus/types';
import type * as OpenApiPlugin from 'docusaurus-plugin-openapi-docs';
import { themes as prismThemes } from 'prism-react-renderer';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const siteUrl = process.env.DOCS_URL?.trim() || 'https://smiski-docs.pages.dev';

const config: Config = {
    title: 'Smiski API Docs',
    tagline: 'API reference for the Smiski meeting platform',
    favicon: 'img/favicon.ico',

    future: {
        v4: true,
    },

    url: siteUrl,
    baseUrl: '/',

    organizationName: 'smiskinext',
    projectName: 'smiski',

    onBrokenLinks: 'warn',

    markdown: {
        hooks: {
            onBrokenMarkdownLinks: 'warn',
        },
    },

    i18n: {
        defaultLocale: 'en',
        locales: ['en'],
    },

    presets: [
        [
            'classic',
            {
                docs: {
                    sidebarPath: './sidebars.ts',
                    // Plugin ID must match the docsPluginId in plugin config below
                    docItemComponent: '@theme/ApiItem',
                    editUrl:
                        'https://github.com/smiskinext/smiski/tree/main/docs/',
                },
                // Blog disabled — not needed for API docs
                blog: false,
                theme: {
                    customCss: './src/css/custom.css',
                },
            } satisfies Preset.Options,
        ],
    ],

    plugins: [
        [
            'docusaurus-plugin-openapi-docs',
            {
                id: 'smiski-api',
                docsPluginId: 'classic',
                config: {
                    smiskiApi: {
                        // Generated by scripts/inject-code-samples.ts before build
                        specPath: 'openapi-with-samples.yaml',
                        outputDir: 'docs/api',
                        sidebarOptions: {
                            groupPathsBy: 'tag',
                            categoryLinkSource: 'tag',
                        },
                        showSchemas: true,
                        showExtensions: false,
                    } satisfies OpenApiPlugin.Options,
                },
            },
        ],
    ],

    themes: ['docusaurus-theme-openapi-docs'],

    themeConfig: {
        image: 'img/docusaurus-social-card.jpg',
        colorMode: {
            defaultMode: 'dark',
            respectPrefersColorScheme: true,
        },
        navbar: {
            title: 'Smiski',
            logo: {
                alt: 'Smiski Logo',
                src: 'img/logo.svg',
            },
            items: [
                {
                    type: 'docSidebar',
                    sidebarId: 'tutorialSidebar',
                    position: 'left',
                    label: 'Docs',
                },
                {
                    label: 'API Reference',
                    position: 'left',
                    to: '/docs/api/smiski-api',
                },
                {
                    href: 'https://github.com/smiskinext/smiski',
                    label: 'GitHub',
                    position: 'right',
                },
            ],
        },
        footer: {
            style: 'dark',
            links: [
                {
                    title: 'Docs',
                    items: [
                        {
                            label: 'Introduction',
                            to: '/docs/intro',
                        },
                        {
                            label: 'API Reference',
                            to: '/docs/api/smiski-api',
                        },
                    ],
                },
                {
                    title: 'More',
                    items: [
                        {
                            label: 'GitHub',
                            href: 'https://github.com/smiskinext/smiski',
                        },
                    ],
                },
            ],
            copyright: `Copyright © ${new Date().getFullYear()} SmiskiNext. Built with Docusaurus.`,
        },
        prism: {
            theme: prismThemes.github,
            darkTheme: prismThemes.dracula,
            // Additional languages for code sample highlighting
            additionalLanguages: ['java', 'bash', 'json'],
        },
    } satisfies Preset.ThemeConfig,
};

export default config;
