import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Generated by `pnpm run gen-api-docs` before Docusaurus loads this config.
// `require` keeps standalone typechecking usable before the generated file exists.
const apiSidebar = require('./docs/api/sidebar.ts')
    .default as SidebarsConfig[string];

const sidebars: SidebarsConfig = {
    tutorialSidebar: [
        'intro',
        { type: 'autogenerated', dirName: 'tutorial-basics' },
        { type: 'autogenerated', dirName: 'tutorial-extras' },
    ],
    apiSidebar,
};

export default sidebars;
