spring:
    kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

app:
    notification:
        kafka:
            invitation-consumer-group: test-notification-meeting-invitations
            invite-invalidated-consumer-group: test-notification-meeting-invite-invalidated
            invitee-responded-consumer-group: test-notification-invitee-responded
