name: Proto

on:
    workflow_call:

permissions:
    contents: read

jobs:
    proto:
        name: Proto checks
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  fetch-depth: 0

            - uses: ./.github/actions/setup

            - uses: bufbuild/buf-action@fd21066df7214747548607aaa45548ba2b9bc1ff # v1.4.0
              with:
                  setup_only: true

            - uses: nrwl/nx-set-shas@afb73a62d26e41464e9254689e1fd6122ee683c1 # v5.0.1

            - name: Run buf-lint on affected
              run: npx nx affected -t buf-lint

            - name: Run buf-breaking on affected
              run: npx nx affected -t buf-breaking
